services:
    postgres-auth-service:
        image: postgres:latest
        container_name: auth-service-db-container
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: auth_service_db
        ports:
            - "5002:5432"
        volumes:
            - postgres_data_auth:/var/lib/postgresql/data
        networks:
            - my_network

    postgres-order-service:
        image: postgres:latest
        container_name: order-service-db-container
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: order_service_db
        ports:
            - "5001:5432"
        volumes:
            - postgres_data_order:/var/lib/postgresql/data
        networks:
            - my_network

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin-container
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: adminpassword
        ports:
            - "5050:80"
        networks:
            - my_network


volumes:
    postgres_data_auth:
    postgres_data_order:


networks:
    my_network:
