services:
  
  order-service-db:
    image: postgres:latest
    container_name: order_service_db_container
    restart: always
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data 
  
  postgres:
    image: postgres:latest
    container_name: keycloak_postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "12345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - start-dev

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
        - "5050:80"

volumes:
  postgres_data:
  orders_db_data:
    
